DROP TABLE IF EXISTS RENTALREMINDERS;
DROP TABLE IF EXISTS RENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS READERS;

CREATE TABLE BOOKS(
isbn VARCHAR(17) NOT NULL,
title VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
publisher VARCHAR(50) NOT NULL,
book_id varchar(36) NOT NULL,
CONSTRAINT BOOKS_PK PRIMARY KEY (book_id)
);

CREATE TABLE READERS (
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
date_of_birth DATE NOT NULL,
phone_number VARCHAR(15) NOT NULL,
email VARCHAR(50) NOT NULL,
reader_id VARCHAR(36) NOT NULL,
CONSTRAINT READERS_PK PRIMARY KEY (reader_id)
);

CREATE TABLE RENTS (
book VARCHAR(36) NOT NULL,
reader VARCHAR(36) NOT NULL,
date_of_rent DATETIME NOT NULL,
date_of_return DATETIME NOT NULL,
returned BOOLEAN NOT NULL,
rent_id VARCHAR(36) NOT NULL,
CONSTRAINT RENTS_PK PRIMARY KEY (rent_id),
CONSTRAINT BOOKSRENTS_FK FOREIGN KEY (book) REFERENCES BOOKS(book_id),
CONSTRAINT READERSRENTS_FK FOREIGN KEY (reader) REFERENCES READERS(reader_id)
);

CREATE TABLE RENTALREMINDERS (
rent VARCHAR(36) NOT NULL,
date_of_reminder DATETIME NOT NULL,
rentalreminder_id VARCHAR(36) NOT NULL,
CONSTRAINT RENTALREMINDERS_PK PRIMARY KEY (rentalreminder_id),
CONSTRAINT RENTSRENTALREMINDERS_FK FOREIGN KEY (rent) REFERENCES RENTS(rent_id)
);